[versions]
project = "0.26.7"
adventureApi = "5.2.0"
dokka = "2.2.0"
kctfork = "0.13.0"
kotest = "6.2.4"
kotestPlugin = "6.2.4"
mockk = "1.14.11"
jetbrainsAnnotations = "26.1.0"
kotlin = "2.4.10"
kotlinxCoroutines = "1.11.0"
kover = "0.9.9"
paperApi = "26.2.build.60-beta"
spotless = "8.10.0"
spotlessKtlint = "1.8.0"

[libraries]
adventure-api = { module = "net.kyori:adventure-api", version.ref = "adventureApi" }
adventure-bom = { module = "net.kyori:adventure-bom", version.ref = "adventureApi" }
adventure-nbt = { module = "net.kyori:adventure-nbt", version.ref = "adventureApi" }
adventure-text-minimessage = { module = "net.kyori:adventure-text-minimessage", version.ref = "adventureApi" }
adventure-text-serializer-gson = { module = "net.kyori:adventure-text-serializer-gson", version.ref = "adventureApi" }
adventure-text-serializer-json-legacy-impl = { module = "net.kyori:adventure-text-serializer-json-legacy-impl", version.ref = "adventureApi" }
adventure-text-serializer-legacy = { module = "net.kyori:adventure-text-serializer-legacy", version.ref = "adventureApi" }
adventure-text-serializer-plain = { module = "net.kyori:adventure-text-serializer-plain", version.ref = "adventureApi" }
jetbrains-annotations = { module = "org.jetbrains:annotations", version.ref = "jetbrainsAnnotations" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }
kctfork-core = { module = "dev.zacsweers.kctfork:core", version.ref = "kctfork" }
kotest-assertions-core = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
kotest-runner-junit5 = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinxCoroutines" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
paper-api = { module = "io.papermc.paper:paper-api", version.ref = "paperApi" }

[plugins]
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
kotest = { id = "io.kotest", version.ref = "kotestPlugin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
